# Generated by Django 5.0.1 on 2024-02-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_address_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
