# Generated by Django 5.0.1 on 2024-02-04 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreveiw',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.product'),
        ),
        migrations.AlterField(
            model_name='productreveiw',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐✭✭✭✭'), (2, '⭐⭐✭✭✭'), (3, '⭐⭐⭐✭✭'), (4, '⭐⭐⭐⭐✭'), (5, '⭐⭐⭐⭐⭐')], default=None),
        ),
    ]
